name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'feat*'

jobs:
  check:
    uses: ./.github/workflows/check.yml

  push:
    runs-on: ubuntu-latest
    needs: [check]

    steps:
      - uses: actions/checkout@v3

      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_ORGANISATION }}/frontend-test
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            release

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REVISION=${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - uses: action/checkout@v3
        with:
          repository: beabee-communityrm/test-deploy
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: |
          git config --global user.name "Deploy bot"
          git config --global user.email "<>"

          echo -n ${{ needs.push.outputs.version }} > FRONTEND_VERSION
          ./update.sh

          git add FRONTEND_VERSION docker-compose.yml
          if ! git diff --quiet --cached; then
            git commit -m "Deploy frontend ${{ needs.push.outputs.version }}"
            git push
          fi
